### ISSUE TITLE
Introduce config file

### ISSUE THREAD

**Issue by informartin** [informartin/VeriSmart#30]
Currently, there exist quite some hard coded values in the code. We should introduce a config file that easily enables users to configure these values.

These should be at least:
- max_gas (maximum gas for single tx)
  - calculating proper gas costs will allow to remove the code size limit parameter as well
- gas_price
- amount of key/value pairs set in a single transaction
  - it would be even better if we could derive that value from max_gas

**Comment by thecodingshrimp** [comment]
additionally:
* file path for ProxyContract.json and InitContract.json in deployLargeContract()
* file path for interrupted-migration.json
* code size

**Comment by thecodingshrimp** [comment]
As discussed in a meeting, use max_gas also for:
* calculating if contract should be deployed as logic or with a proxy contract.
* how many key value pairs should be included in one transaction (calc gas cost for one and two key value pairs and with the difference in gas cost calculate how much the max number of key value pairs in one transaction would be)
* estimate gas cost for deploying storage in portContract function instead of building the contract code first (check if number of keys * 20000 > max_gas)
